PR[4:1] feat: integrate cobra with the --generate flag/command
Agile-Arch-Angels/decentralized-tech-radar_dev pull request #21
Opened 2024-04-08 06:54 UTC by Alex-itu

This integrates the generate command, to generate an HTML file.
You use this by saying 'go run main.go generate '.
Resolves [#59](https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/issues/59)

2024-04-08 06:56 UTC, Slug-Boi commented
Same suggestion as on fetcher see:
https://github.com/Agile-Arch-Angels/decentralized-tech-radar_dev/pull/20#issuecomment-2041988965

2024-04-08 15:39 UTC, August-Brandt approved these changes
Look good

2024-04-09 10:30 UTC, Slug-Boi approved these changes
Looks good. Good to finally have cobra :)

2024-04-09 11:15 UTC, Haruyzal approved these changes

2024-04-09 11:15 UTC, Haruyzal commented on docs/dev_docs/read_and_write.md
I'd like to suggest that we create `dev_docs` and `user_docs` template files for us devs, to ensure consistency in the future. Just a thonk :3

2024-04-09 12:33 UTC, Haruyzal requested changes

2024-04-09 12:33 UTC, Haruyzal commented on docs/dev_docs/read_and_write.md
Think @Alex-itu and I talked about this needing to be updated :)

2024-04-11 07:04 UTC, Alex-itu commented on docs/dev_docs/read_and_write.md
Yep, and it has been updated.

2024-04-11 10:21 UTC, Alex-itu commented
> Nice changes! I've got some suggestions :3

Approve both of does

2024-04-11 10:32 UTC, Haruyzal approved these changes

2024-04-11 16:00 UTC, merged