test: Ensure working E2E test after cobra-integrations
Agile-Arch-Angels/decentralized-tech-radar_dev pull request #24
Opened 2024-04-09 10:10 UTC by Haruyzal

`Fetcher.go` now does not delete the cache-folder every second time we run `go test`.

The E2E-test has been changed so it now uses the Cobra-flags.

The E2E now passes.

Resolves. [#72](https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/issues/72)

2024-04-09 10:27 UTC, Slug-Boi commented on test/cache/ForTesting1.csv
Remove cache via cleanup func and also add this to the gitignore

2024-04-09 10:28 UTC, Slug-Boi requested changes
See my comments

2024-04-11 06:01 UTC, zqueamish approved these changes

2024-04-11 09:52 UTC, Haruyzal commented on src/cache/template1.csv
I cannot see this file in my directory.

2024-04-11 09:52 UTC, Haruyzal commented on test/specfile.txt
Added.

2024-04-11 09:52 UTC, Haruyzal commented on test/cache/ForTesting1.csv
Added.

2024-04-11 10:01 UTC, Haruyzal commented on src/cache/template1.csv
Think I should have deleted it now.

2024-04-11 10:23 UTC, Slug-Boi approved these changes
Looks good now

2024-04-11 17:40 UTC, merged