refactor: use inteface to set the merging strategy
Agile-Arch-Angels/decentralized-tech-radar_dev pull request #46
Opened 2024-04-29 15:56 UTC by August-Brandt

Adds an interface for defining the merging strategy to make it easy add new, and changing, merging strategies.

2024-04-29 19:03 UTC, Haruyzal requested changes
docs nitpicks ❤️

2024-04-29 19:03 UTC, Haruyzal commented on docs/dev_docs/merger_strategies.md
> +## First Come, First Served
```suggestion
## Fcfs: First Come, First Served
```

2024-04-29 19:03 UTC, Haruyzal commented on docs/dev_docs/merger_strategies.md
> +To create a new merge strategy can be done by:
```suggestion
Creating a new merge strategy can be done by:
```

2024-04-30 09:46 UTC, zqueamish approved these changes

2024-05-01 19:03 UTC, merged