docs: update existing docs and add new where it's needed
Agile-Arch-Angels/decentralized-tech-radar_dev pull request #70
Opened 2024-05-13 11:23 UTC by August-Brandt

2024-05-13 11:51 UTC, zqueamish requested changes

2024-05-13 11:51 UTC, zqueamish commented on docs/dev_docs/frontend_thoughtworks_javascript.md
> +To add a library or another script to the Tech Radar you can add it by using requireJS. First, add you script link or library link inside <mark style="background-color: #69a8f5; margin:0 4px; padding
```suggestion
To add a library or another script to the Tech Radar you can add it by using requireJS. First, add your script link or library link inside <mark style="background-color: #69a8f5; margin:0 4px; padding: 0 4px"> ./src/HTML/js/requireConfig.js </mark>.
```

2024-05-13 11:51 UTC, zqueamish commented on docs/user_docs/quickstart.md
> +- Go to the latest release on the repository and download the version that fits your operating system.
```suggestion
- Go to the latest release on the [repository](https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/releases) for this program, and download the version that fits your operating system. 
```

2024-05-14 09:05 UTC, JonasSkjodt approved these changes

2024-05-14 14:54 UTC, Alex-itu approved these changes
Looks good to me, with or without the changes.

2024-05-31 11:04 UTC, August-Brandt commented on docs/user_docs/quickstart.md
> +The merger also includes a cache flag. This will merge all files located in the cache folder:
Technically the merge has no idea if the files are from earlier fetching. It just merges all files in the cache folder

2024-06-01 18:34 UTC, Slug-Boi approved these changes

2024-06-01 18:35 UTC, merged